# === Stage 73: Add a lightweight HTML report export ===
# Project: CraftFlow
import json, html
from pathlib import Path

def export_report(data: dict) -> str:
    """Generates a standalone HTML report from CraftFlow data."""
    project = data.get("project", {})
    materials = data.get("materials", [])
    milestones = data.get("milestones", [])
    
    html_parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'><title>CraftFlow Report</title>",
        "<style>body{font-family:sans-serif;margin:20px}.section{margin-bottom:30px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:6px;text-align:left}</style></head><body>",
        f"<h1>{project.get('name', 'Project')}</h1>",
        f"<div class='section'><h2>Materials</h2><table><tr><th>Name</th><th>Cost</th><th>Status</th></tr>"
    ]
    
    for m in materials:
        html_parts.append(f"<tr><td>{m.get('name', '')}</td><td>${m.get('cost', 0):.2f}</td><td>{m.get('status', 'Pending')}</td></tr>")
    
    html_parts.extend([
        "</table></div>",
        f"<div class='section'><h2>Milestones</h2><ul>"
    ])
    
    for ms in milestones:
        html_parts.append(f"<li>{ms.get('title', '')} - {ms.get('status', 'In Progress')}</li>")
    
    html_parts.extend([
        "</ul></div>",
        f"<p>Total Estimated Cost: ${sum(m.get('cost', 0) for m in materials):.2f}</p>",
        "<footer><small>Generated by CraftFlow</small></footer></body></html>"
    ])
    
    return "".join(html_parts)
